name:                clash-compucolor2
version:             0.1.0
synopsis:            "Compucolor II home computer"
homepage:            https://github.com/gergoerdi/clash-compucolor2
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2020 Gergő Érdi
category:            Hardware

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

library:
  source-dirs: src
  exposed-modules:
    - Hardware.Compucolor2
    
executables:
   clash-issue-1934:
    source-dirs: sim
    main: main.hs
    dependencies:
      - clash-compucolor2
      - clash-ghc
